
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
 <<: *default
 database: development_Imago

test:
 <<: *default
 database: test_Imago

production:
 <<: *default
 database: production_Imago
